import Link from "next/link";
import { ArrowLeft } from "lucide-react";

const sections=[
["1. Information We Collect","Depending on how you use our website, we may collect your name, email, phone number, billing and delivery address, order details, account information, enquiry information, and communications with our team. Payment details may be processed by payment providers."],
["2. How We Use Information","We may use information to process orders and payments, arrange delivery, provide support, respond to enquiries, maintain accounts, improve services, prevent fraud or misuse, and meet applicable legal requirements."],
["3. Cookies & Similar Technologies","Our website may use cookies or similar technologies to keep you signed in, remember preferences, maintain essential functionality, understand usage, and improve the customer experience."],
["4. Sharing Information","Relevant information may be shared with service providers that help operate the website, process payments, deliver orders, provide technology services, or support customers. We do not intend to sell personal information as a standalone commercial product."],
["5. Data Security","We use reasonable technical and organizational measures intended to protect personal information. No online transmission or storage system can be guaranteed completely secure."],
["6. Third-Party Services","Authentication, payment, hosting, analytics, and logistics may be provided by third parties and may be governed by their own privacy policies."],
["7. Your Requests","You may contact NIRA regarding account information, privacy questions, or communications. Transactional, security, and important service messages may still be sent when necessary."],
];
export default function Page(){return <Policy title="Privacy Policy" intro="NIRA Furniture respects your privacy and is committed to handling personal information responsibly when you browse, enquire, create an account, place an order, or communicate with us." sections={sections}/>;}
function Policy({title,intro,sections}:{title:string;intro:string;sections:string[][]}){return <main className="min-h-screen bg-[#F4F0E8] text-[#211E1A]"><Header title={title}/><article className="mx-auto max-w-4xl px-5 py-14 sm:px-8 sm:py-20 lg:py-24"><p className="border-l-2 border-[#927344] pl-5 text-base leading-8 text-[#4F4942] sm:text-lg">{intro}</p>{sections.map(([h,p])=><section key={h} className="border-b border-[#211E1A]/10 py-8"><h2 className="font-serif text-2xl sm:text-3xl">{h}</h2><p className="mt-4 text-sm leading-7 text-[#5F5951]">{p}</p></section>)}<Link href="/contact-support" className="mt-6 inline-flex text-sm font-semibold text-[#927344]">Contact NIRA Support →</Link></article></main>}
function Header({title}:{title:string}){return <header className="border-b border-[#211E1A]/10"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8"><Link href="/" className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#756D63]"><ArrowLeft size={13}/> NIRA Furniture</Link><p className="mt-12 text-[9px] uppercase tracking-[0.3em] text-[#927344]">Customer Policies</p><h1 className="mt-4 font-serif text-4xl sm:text-5xl lg:text-6xl">{title}</h1></div></header>}
